Models/Login.cs
namespace Project.Models
{
    public class Login
    {
        public string? userId { get; set; }
        public string? pwd { get; set; }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class LoginController : Controller
    {
        User_service userservice;
        public LoginController()
        {
            String connString = "Server=" + "127.0.0.1" + ";Database=" + "Project" + ";port=" + "3306" + ";User=" + "root" + ";password=" + "9068";
            userservice = new User_service(connString);
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Mypage()
        {
            var id = HttpContext.Session.GetString("id");
            var user = userservice.Select(id);
            return View(user);
        }

        public IActionResult Delete()
        {
            var id = HttpContext.Session.GetString("id");
            int result = userservice.Delete(id);
            return RedirectToAction("Index");
        }
        public ActionResult Update()
        {
            var id = HttpContext.Session.GetString("id");
            var user = userservice.Select(id);
            return View(user);
        }

        public ActionResult Updatepost(IFormCollection form)
        {
            var Id = form["userId"].ToString();
            var password = form["pwd"].ToString();
            var Name = form["userName"].ToString();
            var Phone = form["userPhone"].ToString();
            var Email = form["userEmail"].ToString();
            var Addr = form["userAddr"].ToString();
            var gender = form["gender"].ToString();

            int result = userservice.Update(Id, password, Name, Phone, Email, Addr, gender);
            TempData["result"] = result;
            return View();
        }

    }
}

Controllers/NewsCRUDController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;
using System.Collections.Generic;


namespace WebApplication1.Controllers//CRUD 요청
{
    public class NewsCRUDController : Controller
    {
        List<NewsTBL> list;
        news_services news;
        public NewsCRUDController()
        {
            String connString = "Server=" + "127.0.0.1" + ";Database=" +
                    "projectDB" + ";port=" + "3306" + ";User=" + "root" + ";password="
                    + "9068";
            news = new news_services(connString);

        }
        public IActionResult Index()//모든 데이터를 다 출력
        {
            list = news.GetNews();
            return View(list); //html 
        }
        public IActionResult Home()//모든 데이터를 다 출력
        {
            list = news.GetNews();
            return View(list); //html 
        }
        public IActionResult Create()
        {
            return View();
        }
        public ActionResult Createpost(IFormCollection form)
        {
            //var newsnum = Convert.ToInt32(form["NewsNum"].ToString());
            var newsarea = form["NewsArea"].ToString();
            var newstitle = form["NewsTitle"].ToString();
            var newscont = form["NewsCont"].ToString();
            //var newspredate = Convert.ToDateTime(form["NewsPreDate"].ToString());
            //var hits = Convert.ToInt32(form["Hits"].ToString());
            var userid = form["UserID"].ToString();

            int result = news.InsertNews(newsarea, newstitle, newscont, userid);
            TempData["result"] = result;
            return View();
        }
        public ActionResult Update(int id)
        {
            var pnews = news.SelectNews(id);
            return View(pnews);
        }
        [HttpPost]
        public ActionResult Updatepost(IFormCollection form)
        {
            var newsnum = Convert.ToInt32(form["NewsNum"].ToString());
            var newsarea = form["NewsArea"].ToString();
            var newstitle = form["NewsTitle"].ToString();
            var newscont = form["NewsCont"].ToString();
            //var newspredate = Convert.ToDateTime(form["NewsPreDate"].ToString());
            //var hits = Convert.ToInt32(form["Hits"].ToString());
            var userid = form["UserID"].ToString();

            int result = news.UpdateNews(newsnum, newsarea, newstitle, newscont, userid);
            TempData["result"] = result;
            return View();
        }
        public ActionResult Details(int id)
        {
            var pnews = news.SelectNews(id);
            return View(pnews);
        }
        public ActionResult Delete(int id)
        {
            var pnews = news.SelectNews(id);
            return View(pnews);
        }
        public ActionResult Deletepost(int id)
        {
            int result = news.DeleteNews(id);
            TempData["result"] = result;
            return View();
        }
        public IActionResult Search(string titleQuery, string areaQuery)
        {
            ViewBag.Title = "Index";
            ViewBag.SearchTitleQuery = titleQuery; // 제목 검색어를 ViewBag에 저장하여 뷰에서 사용
            ViewBag.SearchAreaQuery = areaQuery;   // 지역 검색어를 ViewBag에 저장하여 뷰에서 사용

            // 여기에 검색 로직을 구현합니다.
            // titleQuery 및 areaQuery를 사용하여 뉴스 항목을 검색하고 결과를 Model에 할당합니다.

            List<NewsTBL> searchResults = news.SearchNews(titleQuery, areaQuery);

            return View("Index", searchResults); // "Index" 뷰로 결과를 반환합니다.
        }

    }
}

Controllers/UsersController.cs
using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using Project.Models;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Xml.Linq;
using System.Net.Http;


namespace Project.Controllers
{
    public class UsersController : Controller
    {
        List<Users> list;
        User_service users;

        public UsersController()
        {
            String connString = "Server=" + "127.0.0.1" + ";Database=" + "Project" + ";port=" + "3306" + ";User=" + "root" + ";password=" + "9068";
            users = new User_service(connString);
        }

        public IActionResult Index()
        {
            list = users.GetUsers();
            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }

        public ActionResult CreatePost(IFormCollection form)
        {
            var Id = form["userId"].ToString();
            var password = form["pwd"].ToString();
            var Name = form["userName"].ToString();
            var Phone = form["userPhone"].ToString();
            var Email = form["userEmail"].ToString();
            var Addr = form["userAddr"].ToString();
            var gender = form["gender"].ToString();

            int result = users.Create(Id, password, Name, Phone, Email, Addr, gender);
            TempData["result"] = result;
            return View();
        }

        public IActionResult Detail(string id)
        {
            var user = users.Select(id);
            return View(user);
        }

        public ActionResult Delete(string id)
        {
            int result = users.Delete(id);
            return RedirectToAction("Index");
        }

        //public ActionResult DeletePost(string id)
        //{
        //    int result = users.delete_proc(id);
        //    TempData["result"] = result;
        //    return View();
        //}


       public ActionResult Update(string id)
        {
            var user = users.Select(id);
            return View(user);
        }

        public ActionResult Updatepost(IFormCollection form)
        {
            var Id = form["userId"].ToString();
            var password = form["pwd"].ToString();
            var Name = form["userName"].ToString();
            var Phone = form["userPhone"].ToString();
            var Email = form["userEmail"].ToString();
            var Addr = form["userAddr"].ToString();
            var gender = form["gender"].ToString();

            int result = users.Update(Id, password, Name, Phone, Email, Addr, gender);
            TempData["result"] = result;
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Loginpost(IFormCollection form)
        {
            var id = form["userId"].ToString();
            var password = form["pwd"].ToString();

            int result = users.Login(id, password);
            //users.Mypage(id);

            TempData["result"] = result;

            base.HttpContext.Session.SetString("id", id);

            Console.WriteLine(result);
            return View();
        }
    }
}

Views/Login/Index.cshtml
@{
    //csharp 언어를 이용해 정의
    ViewData["Title"] = "Area Page";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

<!DOCTYPE html>
<html>
<head>

</head>
<style>

    /* Style the top navigation bar */
    .topnav {
        overflow: hidden;
        background-color: #333;
        padding: 10px;
        margin-top: 20px;
        width: 100%;
        font-size: 20px;
    }

        /* Style the topnav links */
        .topnav a {
            float: left;
            display: block;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

            /* Change color on hover */
            .topnav a:hover {
                background-color: #ddd;
                color: black;
            }

    /* Create two unequal columns that floats next to each other */
    /* Left column */
    .leftcolumn {
        float: left;
        width: 75%;
    }

    /* Right column */
    .rightcolumn {
        float: left;
        width: 25%;
        background-color: #f1f1f1;
        padding-left: 6px;
    }

    /* Fake image */
    .fakeimg {
        background-color: #aaa;
        width: 100%;
        padding: 20px;
    }

    /* Add a card effect for articles */
    .card {
        background-color: white;
        padding: 20px;
        margin-top: 20px;
    }

    /* Clear floats after the columns */
    .row::after {
        content: "";
        display: table;
        clear: both;
    }

    /* Footer */
    .footer {
        padding: 0px;
        margin-bottom: -20px;
        background: #ddd;
        width: 100%;
        font-size: 20px;
    }

    iframe {
        position: absolute;
        top: 120px; /* 원하는 수직 위치(px) 설정 */
        left: 35px; /* 원하는 수평 위치(px) 설정 */
    }
</style>


<body>


    <div class="topnav">
        <a href="http://localhost:5286/NewsCRUD/Search?titleQuery=&areaQuery=%EC%84%9C%EC%9A%B8">서울</a>
        <a href="http://localhost:5286/NewsCRUD/Search?titleQuery=&areaQuery=%EA%B2%BD%EA%B8%B0%EB%8F%84">경기도</a>
        <a href="http://localhost:5286/NewsCRUD/Search?titleQuery=&areaQuery=%EA%B0%95%EC%9B%90%EB%8F%84">강원도</a>
        <a href="http://localhost:5286/NewsCRUD/Search?titleQuery=&areaQuery=%EC%B6%A9%EC%B2%AD%EB%8F%84">충청도</a>
        <a href="http://localhost:5286/NewsCRUD/Search?titleQuery=&areaQuery=%EC%A0%84%EB%9D%BC%EB%8F%84">전라도</a>
        <a href="http://localhost:5286/NewsCRUD/Search?titleQuery=&areaQuery=%EA%B2%BD%EC%83%81%EB%8F%84">경상도</a>
        <a href="http://localhost:5286/NewsCRUD/Search?titleQuery=&areaQuery=%EC%A0%9C%EC%A3%BC%EB%8F%84">제주도</a>

    </div>

    <div class="row">
        <div class="leftcolumn">
            <div class="card">
                <h2></h2>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr><tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <iframe width="900" height="500" src="https://www.youtube.com/embed/JzVVm6kT1JU"></iframe>

            </div>

        </div>
        <div class="rightcolumn">
            <div class="card">

                <h2>지역별 뉴스 배너</h2>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <div class="image">
                    <a href="https://www.seoul.co.kr/"><img src="~/images/서울일보.png" alt="Sample Photo" width="200" height="60" /></a>
                </div>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <div class="image">
                    <a href="https://www.kgnews.co.kr/"><img src="~/images/경기신문.png" alt="Sample Photo" width="200" height="60" /></a>
                </div>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <div class="image">
                    <a href="https://www.kwnews.co.kr/"><img src="~/images/강원도민일보.png" alt="Sample Photo" width="200" height="60" /></a>
                </div>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <div class="image">
                    <a href="https://www.ccdailynews.com/"><img src="~/images/충청일보.png" alt="Sample Photo" width="200" height="60" /></a>
                </div>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <div class="image">
                    <a href="https://www.jeollailbo.com/"><img src="~/images/전남일보.png" alt="Sample Photo" width="200" height="60" /></a>
                </div>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <div class="image">
                    <a href="https://www.ksilbo.co.kr/"><img src="~/images/경상일보.png" alt="Sample Photo" width="200" height="60" /></a>
                </div>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <div class="image">
                    <a href="http://www.jejunews.com/"><img src="~/images/제주도민일보.png" alt="Sample Photo" width="200" height="60" /></a>
                </div>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
                <tr>
                    <td><br><br></td> <!-- 공백만큼 줄바꿈 -->
                </tr>
            </div>
        </div>
    </div>
    </div>

    <div class="footer">
        <h2>  <a class="nav-link text-dark" asp-area="" asp-controller="NewsCRUD" asp-action="Made"><p class="custom-font2">MADEby</a></h2>
    </div>

</body>
</html>

Views/Login/Mypage.cshtml
@model Project.Models.Users;
@{
    ViewBag.Title = "Detail";
}
<h2>회원정보</h2>
<table>
    <tr><td>아 이 디</td><td>@Html.DisplayFor(m=>m.userId)</td></tr>
    <tr><td>비밀번호</td><td>@Html.DisplayFor(m=>m.pwd)</td></tr>
    <tr><td>이&emsp;&emsp;름</td><td>@Html.DisplayFor(m=>m.userName)</td></tr>
    <tr><td>휴대전화</td><td>@Html.DisplayFor(m=>m.userPhone)</td></tr>
    <tr><td>이 메 일</td><td>@Html.DisplayFor(m=>m.userEmail)</td></tr>
    <tr><td>주&emsp;&emsp;소</td><td>@Html.DisplayFor(m=>m.userAddr)</td></tr>
    <tr><td>성&emsp;&emsp;별</td><td>@Html.DisplayFor(m=>m.gender)</td></tr>

    <tr>
        <td>
            @Html.ActionLink("수정", "Update", "Login")
            @Html.ActionLink("삭제", "Delete", "Login")
        </td>
    </tr>
</table>

Views/Login/Update.cshtml
@model Project.Models.Users;
@{
    ViewBag.Title = "Update";
}
<h2>회원정보 수정</h2>
@using (Html.BeginForm("Updatepost", "Users", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <dvi class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new{@class = "text=danger"})

        <div class="form-group">
            <h6>아이디</h6>
            <div class="col-md-10">
                @Html.EditorFor(model => model.userId, new {htmlAttributes = new {
            @class = "form-control" }})
            </div>
        </div>

        <dvi class="form-group">
            <h6>비밀번호</h6>
            <dvi class="col-md-10">
                @Html.EditorFor(model => model.pwd, new {htmlAttributes = new {
            @class = "form-control" }})
            </dvi>
        </dvi>

        <dvi class="form-group">
            <div>이름</div>
            <dvi class="col-md-10">
                @Html.EditorFor(model => model.userName, new { htmlAttributes = new {
            @class = "form-control" }})
            </dvi>
        </dvi>

        <dvi class="form-group">
            <div>휴대폰</div>
            <dvi class="col-md-10">
                @Html.EditorFor(model => model.userPhone, new { htmlAttributes = new {
            @class = "form-control" }})
            </dvi>
        </dvi>

        <dvi class="form-group">
            <div>이메일</div>
            <dvi class="col-md-10">
                @Html.EditorFor(model => model.userEmail, new { htmlAttributes = new {
            @class = "form-control" }})
            </dvi>
        </dvi>

        <dvi class="form-group">
            <div>주소</div>
            <dvi class="col-md-10">
                @Html.EditorFor(model => model.userAddr, new { htmlAttributes = new {
            @class = "form-control" }})
            </dvi>
        </dvi>

        <dvi class="form-group">
            <div>성별</div>
            <dvi class="col-md-10">
                @Html.EditorFor(model => model.gender, new { htmlAttributes = new {
            @class = "form-control" }})
            </dvi>
        </dvi>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" id="UpdateCheck" class="btn btn-primary">Save</button>
            </div>
        </div>
    </dvi>
}

Views/Login/Updatepost.cshtml
@{
    ViewBag.Title = "Update Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    int? result = (int?)TempData["result"];
}

@if (result == 1)
{
    <p>데이터 수정 성공</p>
}
else
{
    <p>데이터 수정 실패</p>
}